### ISSUE TITLE
Contributor 2017A7TS1196P who?

### ISSUE THREAD

**Issue by hariharan-srikrishnan** [anirudh-chakravarthy/IR-Assignment#1]
# Who is this person identified by 2017A7TS1196P (Divyam Goel)?

**Comment by anirudh-chakravarthy** [comment]
Can confirm he had no contribution, just formality purposes 👍 I guess he's a friend of one of our group mates, don't really remember...

**Comment by hariharan-srikrishnan** [comment]
Understandable, closing this issue.
